### PR TITLE
Dokku Droplet 1-Click Update

### PR DESCRIPTION
**Pull request by v-aisac**
- Updated Dokku OS Ubuntu 20.04 -> 22.04
- Updated Dokku app version  0.21.4 -> 0.30.6
- Updated Docker-Compose version 1.27.4 -> 2.18.1

Tested successfully :
image

### CODE REVIEW

**Comment by v-aisac** [comment]
image

**Comment by v-aisac** [comment]
it looks like Dokku is running okay, but is inaccessible from outside
image
image

**Comment by josegonzalez** [comment]
> it looks like Dokku is running okay, but is inaccessible from outside image image image

I think that makes sense. That packer domain isn't a valid one, so of course hitting it wouldn't resolve, DNS-wise.

**Comment by v-aisac** [comment]
> > it looks like Dokku is running okay, but is inaccessible from outside image image image
> 
> I think that makes sense. That packer domain isn't a valid one, so of course hitting it wouldn't resolve, DNS-wise.

Thanks for your answers. My bad, I was sticking too much to the old description.
After turning off vhosts and allowing a port for my app and I was able to access it:
image

I will need some time to rewrite Dokku description based on my experience with Dokku so far.

I will include steps like adding public keys, pushing a sample app (ruby-getting-started) and also vhosts disable so people can see it work right away (and also link to dokku domain wiki).

What do you think, should I add/remove some steps?

**Comment by josegonzalez** [comment]
I don't think it should disable vhosts - on boot, we ask a user to set a domain [via motd](https://github.com/dokku/dokku/blob/78f67228bc23138ee5ae43ffe0b4496add5ccc52/plugins/00_dokku-standard/install#L47). The `VHOST` file should probably _not_ be populated for image-based installation so that folks get that message. I feel like a lot of folks will expect a vhost to work otherwise, so disabling it by default seems like a poor experience.

**Comment by v-aisac** [comment]
Hey! I have updated the description a bit, made sure that following every step results in successful deployment and just clicked to publish the new version. We should see it live soon!

**Review by alexeigutium — APPROVED** [review]

**Comment by josegonzalez** [comment]
Should I update my automation to target creating a new PR to this repo every time we make a new release of Dokku?

**Comment by josegonzalez** [comment]
@v-aisac it looks like the description still references a web ui. Is it possible to get that updated? https://marketplace.digitalocean.com/apps/dokku

**Pull request merged**
